[package]
name = "ftzz"
version = "1.0.2"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "File Tree Fuzzer creates a pseudo-random directory hierarchy filled with some number of files."
repository = "https://github.com/SUPERCILEX/ftzz"
keywords = ["tools", "files", "fuzz"]
categories = ["command-line-utilities", "development-tools", "development-tools::testing", "filesystem"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.52"
bytesize = "1.1.0"
clap = { version = "3.0.10", features = ["derive", "wrap_help"] }
clap-num = "1.0.0"
clap-verbosity-flag = "0.4.0"
cli-errors = "0.2.0"
derive_builder = "0.10.2"
exitcode = "1.1.2"
num-format = "0.4.0"
num_cpus = "1.13.1"
rand = { version = "0.8.4", features = ["simd_support"] }
rand_distr = "0.4.3"
rand_xoshiro = "0.6.0"
tokio = { version = "1.15.0", features = ["rt", "parking_lot"] }
tracing = { version = "0.1.30", features = ["release_max_level_info"] }
tracing-chrome = { version = "0.4.0", optional = true }
tracing-log = "0.1.2"
tracing-subscriber = "0.3.8"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { path = "/home/asaveau/Desktop/nix", default-features = false, features = ["fs"] }

[dev-dependencies]
criterion = "0.3.5"
more-asserts = "0.2.2"
rstest = "0.12.0"
seahash = "4.1.0"
stack-buffer = "0.2.0"
tempfile = "3.3.0"

[[bench]]
name = "generator"
harness = false

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
