[package]
name = "ftzz"
version = "1.1.0"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "File Tree Fuzzer creates a pseudo-random directory hierarchy filled with some number of files."
repository = "https://github.com/SUPERCILEX/ftzz"
keywords = ["tools", "files", "fuzz"]
categories = ["command-line-utilities", "development-tools", "development-tools::testing", "filesystem"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.58"
bytesize = "1.1.0"
clap = { version = "3.2.16", features = ["derive"] }
clap-num = "1.0.0"
clap-verbosity-flag = "1.0.1"
cli-errors = "0.3.1"
derive_builder = "0.11.2"
exitcode = "1.1.2"
# TODO use the real itoa once https://github.com/dtolnay/itoa/pull/34 goes through
itoa-const = "1.0.0"
log = { version = "0.4.17", features = ["release_max_level_info"] }
num-format = "0.4.0"
rand = { version = "0.8.5", default-features = false }
rand_distr = "0.4.3"
rand_xoshiro = "0.6.0"
simple_logger = { version = "2.2.0", default-features = false, features = ["colors"] }
tokio = { version = "1.20.1", features = ["rt"] }
tracing = { version = "0.1.36", features = ["release_max_level_off", "log"] }
tracing-chrome = { version = "0.6.0", optional = true }
tracing-subscriber = { version = "0.3.15", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.24.2", default-features = false, features = ["fs"] }

[dev-dependencies]
criterion = "0.3.6"
more-asserts = "0.3.0"
rstest = "0.15.0"
seahash = "4.1.0"
stack-buffer = "0.3.0"
tempfile = "3.3.0"
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
goldenfile = "1.4.3"
public-api = "0.13.0"

[features]
trace = ["tracing-chrome", "tracing-subscriber"]

[[bench]]
name = "generator"
harness = false

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.dr]
inherits = "release"
debug = true
strip = false
