cargo-features = ["strip"]

[package]
name = "ftzz"
version = "1.0.1"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "File Tree Fuzzer creates a pseudo-random directory hierarchy filled with some number of files."
repository = "https://github.com/SUPERCILEX/ftzz"
keywords = ["tools", "files", "fuzz"]
categories = ["command-line-utilities", "development-tools", "development-tools::testing", "filesystem"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.52"
bytesize = "1.1.0"
clap = { version = "3.0.0", features = ["derive", "wrap_help"] }
clap-num = "1.0.0"
clap-verbosity-flag = "0.4.0"
cli-errors = "0.1.0"
derive_builder = "0.10.2"
exitcode = "1.1.2"
log = "0.4.14"
num-format = { version = "0.4.0", features = ["with-system-locale"] }
num_cpus = "1.13.1"
rand = "0.8.4"
rand_distr = "0.4.2"
rand_xorshift = "0.3.0"
simple_logger = { version = "1.16.0", default-features = false, features = ["colors"] }
tokio = { version = "1.15.0", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.23.1"

[dev-dependencies]
criterion = "0.3.5"
more-asserts = "0.2.2"
rstest = "0.12.0"
seahash = "4.1.0"
stack-buffer = "0.1.0"
tempfile = "3.2.0"

[[bench]]
name = "generator"
harness = false

[profile.release]
lto = true
codegen-units = 1
strip = true
