[package]
name = "ftzz"
version = "0.1.3"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "File Tree Fuzzer allows you to create a pseudo-random directory hierarchy filled with some number of files."
repository = "https://github.com/SUPERCILEX/ftzz"
keywords = ["tools", "files", "fuzz"]
categories = ["command-line-utilities", "development-tools", "development-tools::testing", "filesystem"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.44"
clap-num = "0.2.0"
clap-verbosity-flag = "0.3.2"
derive-new = "0.5.9"
exitcode = "1.1.2"
futures = "0.3.17"
log = "0.4.14"
nix = "0.23.0"
num-format = { version = "0.4.0", features = ["with-system-locale"] }
num_cpus = "1.13.0"
rand = "0.8.4"
rand_distr = "0.4.2"
rand_xorshift = "0.3.0"
simple_logger = "1.13.0"
structopt = "0.3.25"
tokio = { version = "1.12.0", features = ["full"] }

[dev-dependencies]
criterion = "0.3.5"
rstest = "0.11.0"
seahash = "4.1.0"
tempfile = "3.2.0"

[[bench]]
name = "generator"
harness = false

[profile.release]
lto = true
codegen-units = 1
