[package]
name = "ftzz"
version = "1.0.2"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "File Tree Fuzzer creates a pseudo-random directory hierarchy filled with some number of files."
repository = "https://github.com/SUPERCILEX/ftzz"
keywords = ["tools", "files", "fuzz"]
categories = ["command-line-utilities", "development-tools", "development-tools::testing", "filesystem"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.55"
bytesize = "1.1.0"
clap = { version = "3.1.2", features = ["derive", "wrap_help"] }
clap-num = "1.0.0"
clap-verbosity-flag = "1.0.0"
cli-errors = "0.3.0"
derive_builder = "0.10.2"
exitcode = "1.1.2"
log = { version = "0.4.14", features = ["release_max_level_info"] }
num-format = "0.4.0"
rand = { version = "0.8.5", features = ["simd_support"] }
rand_distr = "0.4.3"
rand_xoshiro = "0.6.0"
simple_logger = { version = "2.1.0", default-features = false, features = ["colors"] }
tokio = { version = "1.17.0", features = ["rt", "parking_lot"] }
tracing = { version = "0.1.31", features = ["release_max_level_off", "log"] }
tracing-chrome = { git = "https://github.com/SUPERCILEX/tracing-chrome", optional = true }
tracing-subscriber = { version = "0.3.9", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { git = "https://github.com/nix-rust/nix", default-features = false, features = ["fs"] }

[dev-dependencies]
criterion = "0.3.5"
more-asserts = "0.2.2"
rstest = "0.12.0"
seahash = "4.1.0"
stack-buffer = "0.2.0"
tempfile = "3.3.0"

[features]
trace = ["tracing-chrome", "tracing-subscriber"]

[[bench]]
name = "generator"
harness = false

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
